name: Smoke Tests (Firefox)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build project without tests
      - name: Build Snapshot
        run: mvn --batch-mode clean install -T4 -DskipTests

      # Step 5: Run Smoke Tests in Firefox using Xvfb
      - name: Run Smoke Tests (Firefox)
        uses: GabrielBB/xvfb-action@v1
        with:
          run: cd serenity-smoketests && mvn --batch-mode verify -Denvironment=firefox
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_WEBSERVICE_URL: ${{ secrets.JIRA_WEBSERVICE_URL }}
          BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
          BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          LT_USERNAME: ${{ secrets.LT_USERNAME }}
          LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}
