name: Smoke Tests (Chrome)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 using Temurin
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Install Chrome for Testing
      - name: Install Chrome for Testing and Driver
        run: |
          npm install puppeteer
          npx @puppeteer/browsers install chrome@stable

      # Step 5: Build snapshot without tests (parallel build)
      - name: Build Snapshot
        run: mvn --batch-mode clean install -T4 -DskipTests

      # Step 6
